<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace carloancalculator;

use \php\_Boot\HxAnon;
use \php\Boot;
use \maglev\MagLev;

/**
 * Car Loan Calculator
 */
class CarLoanCalculator {

	/**
	 * @var MagLev
	 */
	public $maglev;

	/**
	 * @param MagLev $maglev
	 * 
	 * @return void
	 */
	public function __construct ($maglev) {
		#/src/carloancalculator/CarLoanCalculator.hx:15: characters 3-23
		$this->maglev = $maglev;
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


	}
}

Boot::registerClass(CarLoanCalculator::class, 'carloancalculator.CarLoanCalculator');
Boot::registerMeta(CarLoanCalculator::class, new HxAnon(["obj" => new HxAnon(["SuppressWarnings" => \Array_hx::wrap([\Array_hx::wrap([
	"checkstyle:FieldDocComment",
	"checkstyle:LocalVariableName",
	"checkstyle:MultipleStringLiterals",
	"checkstyle:MagicNumber",
])])])]));
CarLoanCalculator::__hx__init();
